export const equipments = {
  appelDurgence: "Appel d'urgence",
  brasArticule: "Bras articulé",
  canonApeinture: "Canon à peinture",
  carroserieReflechissante: "Carroserie Refléchissante",
  centraleDeRecyclage: "Centrale de recyclage",
  coffreBlinde: "Coffre blindé",
  couchettes: "Couchettes",
  couteauSuisseNumerique: "Couteau suisse Numérique",
  cuisine: "Cuisine",
  equipementsDos: "Equipements dos",
  equipementsDeFurtivite: "Equipements de furtivite",
  equipementsFitness: "Equipement fitness",
  flotteDecentralisee: "Flotte décentralisée",
  fuseeDeDetresse: "Fusée de détresse",
  imprimante3D: "Imprimante 3D",
  kitDeChangementDapparence: "Kit de changement d'apparence",
  kitDeReparation: "Kit de réparation",
  kitDeSoinsDurgence: "Kit de soins d'urgence",
  kitOlfactif: "Kit olfactif",
  laboratoireDanalyse: "Laboratoire d'analyse",
  minibar: "Minibar",
  outilDePiratageNumerique: "Outil de piratage numérique",
  outillageDeChantier: "Outillage de chantier",
  panneauxSolaire: "Panneaux Solaires",
  pass: "Pass",
  projectionHolographique: "Projection Holographique",
  rampeDacess: "Rampe d'accès",
  scannerArayonsX: "Scanner à rayons X",
  siegeEjectable: "Siège Ejectable",
  sondeDeMesures: "Sondes de mesures",
  stationDeJeu: "Station de jeu",
  studioDenregistrement: "Studio d'enregistrement",
  synthetiseurDeSons: "Synthétiseur de sons",
  systemeDarrosage: "Système d'arrosage",
  systemeDeclairage: "Système d'eclairage",
  toboggan: "Toboggan",
  ventouses: "Ventouses",
};
