export const equipments = [
  "Appel d'urgence",
  "Bras articulé",
  "Canon à peinture",
  "Carroserie Refléchissante",
  "Centrale de recyclage",
  "Coffre blindé",
  "Couchettes",
  "Couteau suisse Numérique",
  "Cuisine",
  "Equipements dos",
  "Equipements de furtivite",
  "Equipement fitness",
  "Flotte décentralisée",
  "Fusée de détresse",
  "Imprimante 3D",
  "Kit de changement d'apparence",
  "Kit de réparation",
  "Kit de soins d'urgence",
  "Kit olfactif",
  "Laboratoire d'analyse",
  "Minibar",
  "Outil de piratage numérique",
  "Outillage de chantier",
  "Panneaux Solaires",
  "Pass",
  "Projection Holographique",
  "Rampe d'accès",
  "Scanner à rayons X",
  "Siège Ejectable",
  "Sondes de mesures",
  "Station de jeu",
  "Studio d'enregistrement",
  "Synthétiseur de sons",
  "Système d'arrosage",
  "Système d'eclairage",
  "Toboggan",
  "Ventouses",
];
